### ISSUE TITLE
Support Gnome 3.14

### ISSUE THREAD

**Issue by steelbrain** [mmod/mmod-panel#13]
Just like the title says

**Comment by kirvedx** [comment]
Unfortunately, that's hardly descriptive enough; MMOD-Panel was written on and for 3.14.  

In order to provide you proper support, it'd be helpful to know the following:
- What OS are u using? 
- Logs? 
- Any other extensions installed? 
  
  Just because the extension doesn't work for u does not mean it does not support gnome 3.14.

**Comment by rikkotec** [comment]
Sent from my phone, no idea where the word pub came from...

**Comment by steelbrain** [comment]
I tried using it on Ubuntu 14.10 GNOME Shell 3.14 (installed from the dev PPAs),
When I click the enable button nothing happens, and I do see it in my installed extensions list in gnome-tweak-tool, but with an warning sign, and the enable button disabled.

**Edit:** Any ideas how can I capture some debug info?

**Comment by kirvedx** [comment]
> Any ideas how can I capture some debug info?

Open GUI Syslog and scroll to the bottom of the log for _system_, then restart your shell via `alt+f2`, enter `r`, and hit  `enter`. New messages that include `Gjs` and `mmod-panel` are the relevant messages.

Also using `alt+f2`, enter `lg`, and hit `enter` will open Gnome Looking Glass. Hit the `Extensions` tab and scroll to `MMOD Panel`, and then click `Show errors` (typically next to where it says either `Enabled` or `Disabled`).

## 

Also, other extensions that modify the top bar will interfere; u should remove them if u want MMOD-Panel.

Examples of such extensions:
- Taskbar
- Dash-To-Dock (might be ok now, but interfered previously)
- Similar extensions which attempt to modify the same facilities as MMOD-Panel

**Comment by steelbrain** [comment]
Found it

``` js
TypeError: main.panel.statusArea.aggregateMenu.menu._getMenuItems(...)[9].addMenuItem is not a function
```

**Comment by kirvedx** [comment]
On Tue, 2015-03-24 at 16:30 -0700, Steel Brain wrote:

> Found it
> 
> TypeError: main.panel.statusArea.aggregateMenu.menu._getMenuItems(...)[9].addMenuItem is not a function
> —
> Reply to this email directly or view it on GitHub.

That's a bug with Ubuntu, though it should be fixed with the latest
update.  If you are comfortable modifying a file, I can give you
instruction for getting it working now - and I'll update the code again
with the proper case argument (I probably checked against an array index
existing, instead of whether or not the function member existed).

## 

Rik

**Comment by steelbrain** [comment]
If it'll make the extension work, then sure, why not.

**Comment by kirvedx** [comment]
in `~/.local/share/gnome-shell/extensions/mmod-panel@mmogp.com/lib/mmod/aggregate.js`, specifically line 88, You will see the following:

``` javascript
if( main.panel.statusArea.aggregateMenu.menu._getMenuItems()[9] )
```

It needs to be changed to:

``` javascript
if( main.panel.statusArea.aggregateMenu.menu._getMenuItems()[9] && typeof main.panel.statusArea.aggregateMenu.menu._getMenuItems()[9].addMenuItem === 'function' )
```

Then use the previous instruction to restart the shell.  Afterwards if MMOD-Panel doesn't start automatically, you should be able to enable it.

Please let me know how that works for you.

**Comment by steelbrain** [comment]
I just rebooted my computer and the extension was working again with no modification at all.
Weird, but works.
