### ISSUE TITLE
Add support for gnome 3.16

### ISSUE THREAD

**Issue by Edenhofer** [mmod/mmod-panel#17]
Please add support for the current gnome version. Probably just altering the metadata.json is enaught.

**Comment by kirvedx** [comment]
Alright, will look into this

**Comment by justinnichols** [comment]
This seems fixed as it works on my machine with Gnome Shell 3.16.4.

**Comment by kirvedx** [comment]
Hi there!

Thank you for your feedback.  If you have any further issues, please submit the issue at [MMOD Panel @ Gitlab](https://gitlab.com/mmod/mmod-panel/issues)

Debian won't use github because its not open source - so even though its free I do most of my daily work at gitlab.com.  As a result, all of my projects have been migrated there from the old personally hosted repositories I used to maintain (which albeit were sorely unstable and unreliable).

I never really used github for this repository, it was always just a code mirror for when my network went down.

I can make the issue myself, but for history's sake - and for proper organization and conversation between submitter and assignee - it'd be awesome if you could go submit it at the appropriate repository.

Thanks!
