### ISSUE TITLE
[enhancement] remove prefs option?

### ISSUE THREAD

**Issue by codejeet** [mmod/mmod-panel#19]
This dock would be perfect if i could remove the pointless thing to the right of my running programs/favorites that has the title of the window. Currently there is a 'before prefs' option, but not a remove prefs. 

Also, another good enhancement would be to switch work spaces by scrolling on the bar, much like in dash to dock.

Lastly, a it would be pretty cool to be able to change the padding of the icons to have more/less space.

**Comment by kirvedx** [comment]
On Sat, 2015-06-13 at 17:01 -0700, Gameboy24 wrote:

> This dock would be perfect if i could remove the pointless thing to
> the right of my running programs/favorites that has the title of the
> window. Currently there is a 'before prefs' option, but not a remove
> prefs. 
> 
> —
> Reply to this email directly or view it on GitHub.

Hello,

The problem is that several apps actually only provide a true
'preferences' facility through that button; take terminal or gedit for
instance.

I just feel that by providing such an option that we might be suggesting
to users to remove, albeit at times, necessary components of their
Desktop Environment which contribute to the overall experience for the
end user.

Originally, my own personal version had such a feature; until I noticed
just that issue.

Thoughts?

Best,

## 

Rik

**Comment by kirvedx** [comment]
> Also, another good enhancement would be to switch work spaces by scrolling on the bar, much like > in dash to dock.

I'll take a look at this, thanks for the suggestion.

> Lastly, a it would be pretty cool to be able to change the padding of the icons to have more/less 
> space.

I will see about adding such options to the next release.

**Comment by kirvedx** [comment]
And please refer to the new repository location for further communication regarding this matter

https://code.mmogp.com/mmod/mmod-panel/issues/1
