### ISSUE TITLE
order of items in top-bar keeps changing

### ISSUE THREAD

**Issue by Remington012** [mmod/mmod-panel#21]
I'm using MMOD panel along with the built-in Applications Menu extension in Gnome 3.14 (on Debian jessie).  At least once or twice a day, when I return to my computer and unlock the desktop, I discover that the items in top bar have re-ordered themselves, such that the favorites/shortcuts now appear <b>after</b> the Applications Menu and the "image/title of the active window".

This is especially annoying because the width of the "image/title of the active window" varies, causing the favorites to keep jumping around left-and-right-again as different windows get focused.  Frequently, this causes me to mis-click the wrong favorite since they shift about while I'm moving the mouse pointer (sloppy focus) over towards them.  Here are a few example screen grabs of what the left portion of the top bar can look like when this happens:

![topbars](https://cloud.githubusercontent.com/assets/12207424/8896600/2b511a8e-33b6-11e5-998d-9325cc3d3f8d.png)

The workaround I use to fix this is to open the MMOD panel preferences, check the "Before prefs" checkbox, and then un-check it again -- that effectively re-sorts the items so that the Applications Menu appears first, then the favorites, and then the variable-width "image/title of the active window".  However, it's really annoying to have to keep adjusting that multiple times a day.

**Comment by kirvedx** [comment]
You need to display favorites `Before prefs` in the main settings window.  The reason it's happening I believe is because of the preferences of the application (i.e. the name is longer or shorter depending on the app that is active). Therefore, toggling that switch to show favorites `Before prefs` should resolve that issue.

If that doesnt do it, I'd have to think its that other extension you're using.

If you're still seeing this issue, please resubmit it at [MMOD Panel @ Gitlab](https://gitlab.com/mmod/mmod-panel/issues)
