### ISSUE TITLE
Please update github repo with latest code from https://code.mmogp.com/mmod/mmod-panel.git - can't import to launchpad.net :(

### ISSUE THREAD

**Issue by Baltix** [mmod/mmod-panel#22]
I want to create mmod-panel daily automatic packaging recipe for Ubuntu but can't import code from this GIT repo: https://code.mmogp.com/mmod/mmod-panel.git
Please update github repo with latest code.
See https://answers.launchpad.net/launchpad/+question/271313 for details.

**Comment by kirvedx** [comment]
Hello Mantas,

On 09/11/2015 09:14 PM, Mantas Kriaučiūnas wrote:

> I want to create mmod-panel daily automatic packaging recipe for Ubuntu
> but can't import code from this GIT repo:
> https://code.mmogp.com/mmod/mmod-panel.git
> Please update github repo with latest code.
> See https://answers.launchpad.net/launchpad/+question/271313 for details.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mmod/mmod-panel/issues/22.

This is complete (never heard back so assumed you weren't interested in
figuring out why you couldn't import, so for simplicity I updated the
github repository at github.com/mmod/mmod-panel)

Best,

## 

Richard B Winters
Massively Modified, Inc.
+1(607) 267-1424
mmogp.com

**Comment by kirvedx** [comment]
Hi there!

Thank you for your feedback.  Would you please resubmit this issue at [MMOD Panel @ Gitlab](https://gitlab.com/mmod/mmod-panel/issues)?

Debian won't use github because its not open source - so even though its free I do most of my daily work at gitlab.com.  As a result, all of my projects have been migrated there from the old personally hosted repositories I used to maintain (which albeit were sorely unstable and unreliable).

I never really used github for this repository, it was always just a code mirror for when my network went down.

I can make the issue myself, but for history's sake - and for proper organization and conversation between submitter and assignee - it'd be awesome if you could go submit it at the appropriate repository.

Thanks!
