### ISSUE TITLE
Project inactive, unable to reach author

### ISSUE THREAD

**Issue by franzos** [mmod/mmod-panel#30]
We are interested in the MMOD Panel for our very own desktop Linux distribution, hence we need to fix a couple of bugs and update the plugin to work with the latest Gnome release. Since I'm unable to reach the author, we've made a fork on which we'll be working on. 

https://github.com/PantherMPC/mmod-panel.

Here's what we're working on at the moment:
- Compatibility with GNOME Shell 3.20.4
- Application names beside the individual icons on the Panel [Feature]
- A couple of bux fixes (We're testing on Fedora 24, Gnome Shell 3.20.4)

**Comment by kirvedx** [comment]
Hello there,

That's awesome that there is interest.  I had kept the latest code on the mmogp.com repository, but I had to take down my clusters and hadn't updated this repository with the latest work.  At least I'm fairly positive of that.

I intend to update it, but I would love to include anything that others have contributed or would like to.

It is going to take me a good couple of weeks to get everything in order, but I have not abandoned the project quite yet!

**Comment by franzos** [comment]
@rikkotec great to hear that you're still working on this 👍

**Comment by kirvedx** [comment]
Its been a while, but after disappearing again I've reorganized the project and permanently migrated to gitlab.com.

I was hosting it on a personally maintained network - but I've accepted the fact that I cannot keep my network  up reliably, and so I've migrated all my projects to Gitlab.  

Initially this was because it imported everything, including my wiki's, perfectly - thought now I stick with it because Debian dislikes anything not open source, and while free - github fits that bill.

As I now work in Gitlab on a daily basis, that's where the project will be maintained.  I may eventually setup proper code mirroring through Gitlab's Github integration, but that will be some time to come.

Therefore, any issues or requests or anything, that you may have, please submit [here](https://gitlab.com/mmod/mmod-panel/issues)

Thanks!
